import sys
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.ticker as ticker

import numpy as np

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import uic
import PPSclass as PPS

class MplCanvas(FigureCanvas):
    def __init__(self, parent=None, width=5, height=4, dpi=100):
        fig = Figure(figsize=(width, height), dpi=dpi)
        self.axes = fig.add_subplot(111)
        super(MplCanvas, self).__init__(fig)
        fig.tight_layout()

class PPS_App(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 697)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.open_btn.setObjectName("open_btn")

        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(130, 20, 101, 31))
        self.save_btn.setIconSize(QtCore.QSize(16, 16))
        self.save_btn.setObjectName("save_btn")

        self.width_slid = QtWidgets.QSlider(self.centralwidget)
        self.width_slid.setGeometry(QtCore.QRect(94, 110, 311, 22))
        self.width_slid.setMinimum(1)
        self.width_slid.setMaximum(500)
        self.width_slid.setProperty("value", 100)
        self.width_slid.setOrientation(QtCore.Qt.Horizontal)
        self.width_slid.setObjectName("width_slid")

        self.height_slid = QtWidgets.QSlider(self.centralwidget)
        self.height_slid.setGeometry(QtCore.QRect(94, 150, 311, 22))
        self.height_slid.setMinimum(1)
        self.height_slid.setMaximum(500)
        self.height_slid.setProperty("value", 100)
        self.height_slid.setOrientation(QtCore.Qt.Horizontal)
        self.height_slid.setObjectName("height_slid")

        self.width_lbl = QtWidgets.QLabel(self.centralwidget)
        self.width_lbl.setGeometry(QtCore.QRect(34, 110, 61, 21))
        self.width_lbl.setBaseSize(QtCore.QSize(0, 0))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.width_lbl.setFont(font)
        self.width_lbl.setObjectName("width_lbl")

        self.height_lbl = QtWidgets.QLabel(self.centralwidget)
        self.height_lbl.setGeometry(QtCore.QRect(30, 140, 61, 31))
        self.height_lbl.setBaseSize(QtCore.QSize(0, 0))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.height_lbl.setFont(font)
        self.height_lbl.setObjectName("height_lbl")

        self.quantity_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.quantity_btn.setGeometry(QtCore.QRect(40, 210, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quantity_btn.setFont(font)
        self.quantity_btn.setObjectName("quantity_btn")

        self.density_btn = QtWidgets.QRadioButton(self.centralwidget)
        self.density_btn.setGeometry(QtCore.QRect(40, 240, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.density_btn.setFont(font)
        self.density_btn.setObjectName("density_btn")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(183, 200, 16, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.method_lbl = QtWidgets.QLabel(self.centralwidget)
        self.method_lbl.setGeometry(QtCore.QRect(210, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.method_lbl.setFont(font)
        self.method_lbl.setObjectName("method_lbl")

        self.method_list = QtWidgets.QComboBox(self.centralwidget)
        self.method_list.setGeometry(QtCore.QRect(210, 220, 201, 22))
        self.method_list.setObjectName("method_list")
        self.method_list.addItem("")
        self.method_list.setItemText(0, "random")
        self.method_list.addItem("")

        self.particle_value = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.particle_value.setGeometry(QtCore.QRect(70, 270, 62, 22))
        self.particle_value.setObjectName("particle_value")
        self.a_lbl = QtWidgets.QLabel(self.centralwidget)
        self.a_lbl.setGeometry(QtCore.QRect(210, 265, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.a_lbl.setFont(font)
        self.a_lbl.setObjectName("a_lbl")
        self.a_box = QtWidgets.QTextEdit(self.centralwidget)
        self.a_box.setGeometry(QtCore.QRect(240, 260, 51, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.a_box.setFont(font)
        self.a_box.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.a_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.a_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.a_box.setObjectName("a_box")

        ######################## canvas
        self.canvas = MplCanvas(self, width=12, height=12, dpi=100)

        self.scatter_box = QtWidgets.QWidget(self.centralwidget)
        self.scatter_box.setGeometry(QtCore.QRect(500, 70, 550, 550))
        self.scatter_box.setStyleSheet("background-color: rgb(107, 211, 204);")
        self.scatter_box.setObjectName("scatter_box")


        self.adjustments_group = QtWidgets.QGroupBox(self.centralwidget)
        self.adjustments_group.setGeometry(QtCore.QRect(10, 70, 461, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adjustments_group.setFont(font)
        self.adjustments_group.setObjectName("adjustments_group")
        self.width_value_label = QtWidgets.QLabel(self.adjustments_group)
        self.width_value_label.setGeometry(QtCore.QRect(410, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.width_value_label.setFont(font)
        self.width_value_label.setObjectName("width_value_label")
        self.height_value_label = QtWidgets.QLabel(self.adjustments_group)
        self.height_value_label.setGeometry(QtCore.QRect(410, 76, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.height_value_label.setFont(font)
        self.height_value_label.setObjectName("height_value_label")
        self.run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.run_btn.setGeometry(QtCore.QRect(320, 330, 121, 31))
        self.run_btn.setObjectName("run_btn")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(10, 380, 461, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        ############### progress bar ################
        self.progress_bar.setFont(font)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        ####################################################
        self.terminal_box = QtWidgets.QWidget(self.centralwidget)
        self.terminal_box.setGeometry(QtCore.QRect(10, 420, 461, 181))
        self.terminal_box.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.terminal_box.setObjectName("terminal_box")

        ################### TIMESTEP SLIDER ####################################
        self.timestep_slid = QtWidgets.QSlider(self.centralwidget)
        self.timestep_slid.setGeometry(QtCore.QRect(580, 40, 451, 22))
        self.timestep_slid.setOrientation(QtCore.Qt.Horizontal)
        self.timestep_slid.setObjectName("timestep_slid")
        self.timestep_lbl = QtWidgets.QLabel(self.centralwidget)
        self.timestep_lbl.setGeometry(QtCore.QRect(500, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.timestep_lbl.setFont(font)
        self.timestep_lbl.setObjectName("timestep_lbl")
        self.timestep_value_lbl = QtWidgets.QLabel(self.centralwidget)
        self.timestep_value_lbl.setGeometry(QtCore.QRect(770, 20, 31, 21))
        font = QtGui.QFont()
        font.setItalic(False)
        self.timestep_value_lbl.setFont(font)
        self.timestep_value_lbl.setObjectName("timestep_value_lbl")

        self.visualization_group = QtWidgets.QGroupBox(self.centralwidget)
        self.visualization_group.setGeometry(QtCore.QRect(490, 10, 571, 621))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.visualization_group.setFont(font)
        self.visualization_group.setObjectName("visualization_group")
        self.visualization_group.raise_()
        self.adjustments_group.raise_()
        self.open_btn.raise_()
        self.save_btn.raise_()
        self.width_slid.raise_()
        self.height_slid.raise_()
        self.width_lbl.raise_()
        self.height_lbl.raise_()
        self.quantity_btn.raise_()
        self.density_btn.raise_()
        self.line.raise_()
        self.method_lbl.raise_()
        self.method_list.raise_()
        self.particle_value.raise_()
        self.a_lbl.raise_()
        self.a_box.raise_()
        self.scatter_box.raise_()
        self.run_btn.raise_()
        self.progress_bar.raise_()
        self.terminal_box.raise_()
        self.timestep_slid.raise_()
        self.timestep_lbl.raise_()
        self.timestep_value_lbl.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_btn.setText(_translate("MainWindow", "Open Data File"))
        self.save_btn.setText(_translate("MainWindow", "Save Data to..."))
        self.width_lbl.setText(_translate("MainWindow", "Width:"))
        self.height_lbl.setText(_translate("MainWindow", "Height:"))
        self.quantity_btn.setText(_translate("MainWindow", "Particle Quantity"))
        self.density_btn.setText(_translate("MainWindow", "Particle Density"))
        self.method_lbl.setText(_translate("MainWindow", "Choose the method:"))
        self.method_list.setItemText(1, _translate("MainWindow", "center"))
        self.a_lbl.setText(_translate("MainWindow", "a="))
        self.adjustments_group.setTitle(_translate("MainWindow", "Adjustments:"))
        self.width_value_label.setText(_translate("MainWindow", "value"))
        self.height_value_label.setText(_translate("MainWindow", "value"))
        self.run_btn.setText(_translate("MainWindow", "RUN"))
        self.timestep_lbl.setText(_translate("MainWindow", "Time step:"))
        self.timestep_value_lbl.setText(_translate("MainWindow", "value"))
        self.visualization_group.setTitle(_translate("MainWindow", "Visualization:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = PPS_App()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
